version: '3.7'
services:
  msmetko:
    image: svelte-test
    container_name: personal-website
    build:
        dockerfile: Dockerfile
        context: .
    restart: always
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.msmetko.rule=Host(`msmetko.xyz`)"
        - "traefik.http.routers.msmetko.entrypoints=websecure"
        - "traefik.http.routers.msmetko.tls=true"
        - "traefik.http.routers.msmetko.tls.certresolver=le"
        - "traefik.http.services.msmetko.loadbalancer.server.scheme=http"
        - "traefik.http.services.msmetko.loadbalancer.server.port=5000"
        - "traefik.docker.network=traefik_default"
    ports:
        - "5000:5000"
    networks:
        - traefik_default

networks:
    traefik_default:
        external: true
