name: deploy on production
on:
    # Deploy only when pushed directly to the master
    push:
        branches:
            - master
jobs:
    deploy:
        name: deploy
        runs-on: ubuntu-latest
        steps:
            - name: ssh to my production server and do manual deploy
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  port: ${{ secrets.PORT }}
                  key: ${{ secrets.SSH_KEY }}
                  script: |
                      cd personal-website &&
                      sudo docker-compose down &&
                      git checkout master &&
                      git pull &&
                      sudo docker-compose build &&
                      sudo docker-compose up -d
                      # cleanup
                      # sudo docker images | grep '<none>' | sed -E 's/\s+/ /g' | cut -d ' ' -f 3 | xargs -I {} sudo docker rmi {} -f

